[book]
authors = ["techyCoder81"]
language = "en"
multilingual = false
src = "src"
title = "hdr-changelog"

[output.html]
site-url = "/hdr-changelog/"
default-theme = "ayu"

[output.html.fold]
enable = true
level = 0