[book]
authors = ["Askew"]
language = "en"
multilingual = false
src = "src"
title = "HDR Data"

[output.html]
site-url = "/hdr-data/"
default-theme = "ayu"
copy-fonts = true

[output.html.fold]
enable = true
level = 0