[book]
authors = ["techyCoder81", "Askew"]
language = "en"
multilingual = false
src = "src"
title = "HDR Master Changelog"

[output.html]
site-url = "/hdr-changelog/"
default-theme = "ayu"
copy-fonts = true

[output.html.fold]
enable = true
level = 0